"use client";
import { useEffect } from "react";
import "./globals.css";
import Providers from "@/store/provider";
import { PersistGate } from "redux-persist/integration/react";
import { persistor } from "@/store";
import { AnimatePresence } from "framer-motion";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // if (typeof window !== "undefined") {
  //     const script = document.createElement("script");
  //     script.src = "https://cdn.jsdelivr.net/npm/eruda";
  //     script.onload = () => {
  //       // @ts-ignore
  //       eruda.init();
  //     };
  //     document.body.appendChild(script);
  //   }
  return (
    <html lang="en">
      <body>
        <Providers>
          <PersistGate loading={null} persistor={persistor}>
            <AnimatePresence mode="wait">{children}</AnimatePresence>
          </PersistGate>
        </Providers>
      </body>
    </html>
  );
}
